//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asp.NETMVCCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class circuitos
    {
        public int idcircuito { get; set; }
        public string zona { get; set; }
        public string subestacion { get; set; }
        public Nullable<int> circuito { get; set; }
        public string secir { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> clientes { get; set; }
        public Nullable<int> banco { get; set; }
        public Nullable<int> demandamaxima { get; set; }
        public Nullable<int> demandaminima { get; set; }
        public Nullable<decimal> demandamedia { get; set; }
        public string nivtension { get; set; }
        public string urbanorural { get; set; }
        public Nullable<decimal> porcentajerural { get; set; }
        public Nullable<decimal> dekma { get; set; }
        public Nullable<decimal> dekms { get; set; }
        public Nullable<decimal> kmtot { get; set; }
        public string ciage { get; set; }
    }
}
