//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asp.NETMVCCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contingencias
    {
        public int idcontingencia { get; set; }
        public string tipo { get; set; }
        public string proceso { get; set; }
        public string zona { get; set; }
        public Nullable<int> circuito { get; set; }
        public string categoria { get; set; }
        public Nullable<long> noeconomico { get; set; }
        public string rpe { get; set; }
        public string nombre { get; set; }
        public Nullable<System.DateTime> entrada { get; set; }
        public Nullable<System.DateTime> salida { get; set; }
        public Nullable<int> tiempo { get; set; }
        public string activo { get; set; }
        public string actividad { get; set; }
        public string supervisor { get; set; }
    }
}
