//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asp.NETMVCCRUD.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataBaseModelo : DbContext
    {
        public DataBaseModelo()
            : base("name=DataBaseModelo")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<circuitos> circuitos { get; set; }
        public virtual DbSet<contingencias> contingencias { get; set; }
        public virtual DbSet<subestaciones> subestaciones { get; set; }
        public virtual DbSet<trabajadores> trabajadores { get; set; }
        public virtual DbSet<vehiculos> vehiculos { get; set; }
    }
}
