//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asp.NETMVCCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class subestaciones
    {
        public int idsub { get; set; }
        public string cveese { get; set; }
        public string inmueble { get; set; }
        public string cveareasuperior { get; set; }
        public string areasuperior { get; set; }
        public string rperesponsablect { get; set; }
        public string nombreresponsablect { get; set; }
        public string apellidopatresponsablect { get; set; }
        public string apellidomatresponsablect { get; set; }
        public string rperesponsablepc { get; set; }
        public string nombreresponsablepc { get; set; }
        public string apellidopatresponsablepc { get; set; }
        public string apellidomatresponsablepc { get; set; }
        public string estado { get; set; }
        public string alcaldiamun { get; set; }
        public string localidad { get; set; }
        public Nullable<int> cp { get; set; }
        public string callenumero { get; set; }
        public string colonia { get; set; }
    }
}
