//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asp.NETMVCCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trabajadores
    {
        public int idtrabajador { get; set; }
        public string cvezona { get; set; }
        public string zona { get; set; }
        public string tipocontrato { get; set; }
        public string rpe { get; set; }
        public string nombre { get; set; }
        public string sexo { get; set; }
        public string tipotrab { get; set; }
        public string plaza { get; set; }
        public string categoria { get; set; }
        public string ramaactividad { get; set; }
        public Nullable<int> cenco { get; set; }
        public string centrocosto { get; set; }
        public string ubicacion { get; set; }
        public Nullable<int> ct { get; set; }
        public string centrotrabajo { get; set; }
    }
}
