//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asp.NETMVCCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehiculos
    {
        public int idvehiculo { get; set; }
        public Nullable<long> noeconomico { get; set; }
        public string tipovehiculo { get; set; }
        public string descvehiculo { get; set; }
        public string denominacion { get; set; }
        public string clvehic { get; set; }
        public string descclvehiculo { get; set; }
        public string noinventario { get; set; }
        public string noserie { get; set; }
        public string centroemplazamiento { get; set; }
        public string desccentroemplazamiento { get; set; }
        public string tipouso { get; set; }
        public string puestotrabajo { get; set; }
        public string descpuestotrabajo { get; set; }
        public string desccategoriapuestotrabajo { get; set; }
        public string campoclasificacion { get; set; }
        public string division { get; set; }
        public string descdivision { get; set; }
        public string puestotrabajoresponsable { get; set; }
        public string descpuestotrabajoresponsable { get; set; }
        public string placas { get; set; }
        public string traccion { get; set; }
    }
}
